#!/bin/bash
# Change all file extension from $1 to $2
# usage ./rename $1 $2

function usage {
	echo 'usage "rename $1 $2"'
	exit 1
}

[[ $# -ne 2 ]] && usage

for i in *.$1; do mv "$i" "`basename $i .$1`.$2"; done